### ISSUE TITLE
How to restart the network with `service` module ?

### ISSUE THREAD

**Issue by chusiang** [ansible-tw/AMA#18]
We can restart the network with `service` module, but the **systemd** will Ignoring the "args".

> [service \- Manage services\. — Ansible Documentation](http://docs.ansible.com/ansible/service_module.html)

- example playbook.

  ```yaml
  $ cat test.yml
  - name: testing restart network with service 
    hosts: all
    tasks:
    - name: restart network
      become: true
      service:
        name: network
        state: restarted
        args: eth0
  ```

- Run this playbook on CentOS 7.

  ```
  $ ansible-playbook test.yml
  
  PLAY [testing restart network with service] **************************************************************
  
  TASK [Gathering Facts] ***********************************************************************************
  ok: [default]
  
  TASK [restart network] ***********************************************************************************
   [WARNING]: Ignoring "args" as it is not used in "systemd"
  
  changed: [default]
  
  PLAY RECAP ***********************************************************************************************
  default                    : ok=2    changed=1    unreachable=0    failed=0
  ```
