### ISSUE TITLE
透過 playbook 建立使用者時隨機產生密碼的作法

### ISSUE THREAD

**Issue by evechen0424** [ansible-tw/AMA#19]
## 使用情境

要設計一個安裝產品的 playbook 時，遇到需要建立 mysql 帳號的狀況。

主要是要針對不同產品去建立專屬的帳號，最後須將此密碼填入某個 php 中。

如果把密碼直接寫死在 playbook 中，執行者可能會貪方便而不去調整密碼，造成每個機器所安裝的產品都是使用同一組密碼。

一開始時，使用了 Vars prompt 的方式，執行 playbook 時預先要填入隨機的變數，藉此讓密碼有所區別。

後來考慮到 playbook 可能會重複執行還有其他使用這個 playbook 的 RD 方便，最後用 register 的方式來處理這個問題。

## task.yml

```
  - name: Create a password with shell
    shell:  "head /dev/urandom | tr -dc A-Za-z0-9 | head -c 13"
    register: mysql_password

  - name: Create a mysql user
    mysql_user: 
      name: "product"
      password: "{{ mysql_password.stdout }}"
      priv: "product.*:ALL,GRANT"
      login_user: root
      login_password: 123456
      state: present
```

特別感謝 Ansible Taiwan - Aweimeow (@aweimeow)、ChengWei Chen (@theqwan-chengwei) 的建議。
