### ISSUE TITLE
module - mysql_db 在遇到有 dot 的 database name (例如：stg.dbname ) 時會回傳錯誤訊息

### ISSUE THREAD

**Issue by theqwan-chengwei** [ansible-tw/AMA#28]
在使用 ansible module 的 mysql_db 時有一個小雷，如果你欲建立的 database name 包含有 dot 時，例如「stg.dbname」，可能會遇到 ansible 回傳下面的錯誤訊息 `MySQL does not support database with more than 1 dots`。

不論你是加上 `''` 或 `""` 或 `\.` 或將 database name 放進 var 再送進 task，都無法解決此問題，正確的解答在此，請參閱
https://github.com/ansible/ansible/blob/devel/lib/ansible/module_utils/database.py#L121

必須在 database name 的前後補上 `，才能順利建立 database，如下範例：

```
  tasks:
    - name: "Create a new database with name"
      mysql_db:
        name: "`stg.dbname`"
        state: present
```

感謝 Ansible Taiwan 社群內的 `印章 Seal` 提供解答！
