### ISSUE TITLE
透過 ansible 完成 Linux hostname設定

### ISSUE THREAD

**Issue by Ichiro-Hu** [ansible-tw/AMA#31]
我的需求：目前準備要對公司 Linux 系統主機導入IDM（FreeIPA)方案，需要針對hostname設定為 FQDN格式，因此大量變更主機hostname 的需求就孕育而生~
我的環境：CentOS 6 版
我的 LAB 環境：vm centos6 三台
Ansible 步驟：
1.  完成inventory file 設定檔，且內容具有 hostname vars

```
[node]
192.168.1.1 hostname=node-1.domain.com
192.168.1.2 hostname=node-2.domain.com
192.168.1.3 hostname=node-3.domain.com
```

2.  編輯 Ansible playbook file:hostname.yml

```
---                                                                         
- hosts: node
  become: true
  tasks:

  - name: cmd hostname -v
    command: 'hostname -v {{hostname}}'
    when: ansible_distribution_major_version == '6'

  - name: Set hostname file
    lineinfile:
      path: /etc/sysconfig/network
      regexp: '^HOSTNAME'
      line: 'HOSTNAME={{hostname}}'
    when: ansible_distribution_major_version == '6'

```
3.  執行 ansible playbook 完成使命。

心得：
1. 透過 vars 變數，可以完成不少工作，我是參考官網Doc [網址](https://docs.ansible.com/ansible/latest/user_guide/intro_inventory.html#)。
2. ansible 有個 hostname_module，也可以善加使用，應該可以取代我上述的 command task。
3. 因為CentOS 6 & 7 設定hostname 命令與設定檔路境皆不相同，所以判斷式 _**when: ansible_distribution_major_version == '6'**_ 是有必要的。
