### ISSUE TITLE
讀取yml作為變數，取值的問題

### ISSUE THREAD

**Issue by changchichung** [ansible-tw/AMA#36]
我想幫某個部門的user建立各自的目錄
然後部門的資料已經轉成 yml 檔案
所以我先load yml 檔案進來作為變數來源

```
- name: load teams.yml
  tags:
    - env
    - debug
  include_vars:
    file: files/abc/teams.yml
```

debug var=teams 的內容大概是這樣

```
ok: [pc056.abc.com] => {
    "teams": [
        {
            "chinese_name": "秘書部", 
            "description": "秘書部", 
            "gid": 10125, 
            "location": [
                "hq"
            ], 
            "name": "aa", 
            "users": [
                "chenhu", 
                "chouf", 
                "huangyi", 
                "yehy", 
                "wany"
            ]
        }, 
        {
            "chinese_name": "財務會計處", 
            "description": "財務會計處", 
            "gid": 10126, 
            "location": [
                "hq"
            ], 
            "name": "ac", 
            "users": [
                "chenchiao", 
                "chengc", 
                "cheny", 
                "hsuli", 
                "liji", 
                "liwa", 
                "changchi"
            ]
        }, 
```

然後我想幫秘書部這些user 建立目錄
我是這樣寫

```
- name: create pipenv working directory
  tags:
    - debug
    - pipenv
  file:
    path: "/home/{{item.users}}/D"
    owner: "{{ item.users }}"
    group: "{{ item.users }}"
    state: directory
  when: item.name == "aa"
  with_items: "{{ teams }}"
```

可是執行結果會發生錯誤 (底下這不是秘書部的資料，是我隨便抓一個部門的錯誤訊息)

```
failed: [pc056.abc.com] (item={u'users': [u'tsengyi', u'chenp', u'lich', u'hsiaoch', u'wangr', u'dengm', u'guot', u'hsul', u'linm'], u'chinese_name': u'\u7269\u6d41\u90e8', u'description': u'\u7269\u6d41\u90e8', u'gid': 10159, u'location': [u'hq'], u'name': u'dc'}) => {"changed": false, "gid": 0, "group": "root", "item": {"chinese_name": "物流部", "description": "物流部", "gid": 10159, "location": ["hq"], "name": "dc", "users": ["tsengyi", "chenp", "lich", "hsiaoch", "wangr", "dengm", "guot", "hsul", "linm"]}, "mode": "0755", "msg": "chown failed: failed to look up user ['tsengyi', 'chenp', 'lich', 'hsiaoch', 'wangr', 'dengm', 'guot', 'hsul', 'linm']", "owner": "root", "path": "/home/[u'tsengyi', u'chenp', u'lich', u'hsiaoch', u'wangr', u'dengm', u'guot', u'hsul', u'linm']/D/depot", "size": 4096, "state": "directory", "uid": 0}
```

請問是哪邊出了問題？

**Comment by tsengeagle** [comment]
因為users在你的資料結構裡面是list，而owner和group的屬性應該只能吃字串

參考

```yaml
- hosts: lab1
  become: yes
  vars:
    teams:
      - name: team1
        users:
          - user1
          - user2
      - name: team2
        users: 
          - user3
          - user4
  tasks:
    - name: add user
      user:
        name: "{{ item }}"
      with_items: "{{ teams[0].users }}"
```

**Comment by tsengeagle** [comment]
可以把file抽出來變成include_tasks

* main.yml

```yaml
- hosts: lab1
  become: yes
  vars:
    teams:
      - name: team1
        users:
          - user1
          - user2
      - name: team2
        users: 
          - user3
          - user4
  tasks:
    # - name: add user
    #   user:
    #     name: "{{ item }}"
    #   with_items: "{{ teams[0].users }}"

    - name: add user for {{ item.name }}
      include_tasks: child.yml
      vars:
        team: "{{ item }}"
      with_items: "{{ teams }}"
```

* child.yml

```yaml
- debug:
    msg: "{{ team }}"

- user:
    name: "{{ item }}"
  with_items: "{{ team.users }}"
```

**Comment by changchichung** [comment]
我後來有成功了
```
- name: load teams.yml
  tags:
    - env
    - dcusers
  include_vars:
    file: files/abc/teams.yml

- name: set dc_users
  tags:
    - dcusers
  set_fact: dc_users="{{ item.users }}"
  when: item.name == 'dc'
  with_items: "{{ teams }}"

- name: add dc_users to depotusers group
  tags:
    - dcusers
  user:
    name: "{{ item }}"
    groups: depotusers
    append: yes
  with_items: " {{ dc_users }} "

```

如同前面先進所說，因為取出來的 users 是一個 list ，沒辦法直接拿來用
所以先把這個list 指定給一個local var (dc_users)
然後再用這個 dc_users 來跑 with_items 就可以了

謝謝各位指點
