### ISSUE TITLE
ansible template 的問題

### ISSUE THREAD

**Issue by changchichung** [ansible-tw/AMA#38]
我在 roles/abc/default/main.yml 內定義了一些變數如下
```
bo_gw_nets:
  - [name: hq, bo_wan_networks: 1.1.1.0, bo_wan_gw: 1.1.1.1, bo_lan_networks: 192.168.20.0]
  - [name: ty, bo_wan_networks: 2.2.2.0, bo_wan_gw: 2.2.2.2, bo_lan_networks: 192.168.34.0]
  - [name: jm, bo_wan_networks: 3.3.3.0, bo_wan_gw: 3.3.3.3, bo_lan_networks: 192.168.35.0]
  - [name: tc, bo_wan_networks: 4.4.4.0, bo_wan_gw: 4.4.4.4, bo_lan_networks: 192.168.40.0]
  - [name: tn, bo_wan_networks: 5.5.5.0, bo_wan_gw: 5.5.5.5, bo_lan_networks: 192.168.60.0]
  - [name: kh, bo_wan_networks: 6.6.6.0, bo_wan_gw: 6.6.6.6, bo_lan_networks: 192.168.70.0]
  - [name: sd, bo_wan_networks: 7.7.7.0, bo_wan_gw: 7.7.7.7, bo_lan_networks: 192.168.80.0]
  - [name: dc, bo_wan_networks: 8.8.8.0, bo_wan_gw: 8.8.8.8, bo_lan_networks: 192.168.28.0]
  - [name: tt, bo_wan_networks: 9.9.9.0, bo_wan_gw: 9.9.9.9, bo_lan_networks: 192.168.28.0]
```
然後我想在playbook中，用這些變數來產生文件
```
- name: create firewall.user file using template
  template:
    src: firewall.user.j2
    dest: /tmp/firewall.user
```
j2 template 長這樣 iptables 那邊的語法不重要，先測試而已
```
iptables -F
iptables -P FORWARD DROP
iptables -P INPUT DROP
iptables -P OUTPUT ACCEPT
iptables -P FORWARD ACCEPT
iptables --delete-chain forward
iptables --delete-chain forward_fule
iptables --delete-chain input
iptables --delete-chain input_rule
iptables --delete-chain output
iptables --delete-chain output_rule
iptables -A INPUT --src 127.0.0.1 --dst 127.0.0.1 -j ACCEPT


{% for x in bo_gw_nets %}
iptables -t nat -A POSTROUTING -o eth1 -s  {{x.name}}/32 -j MASQUERADE
{% endfor %}
```
可是執行的結果會發生錯誤
```
"msg": "AnsibleUndefinedVariable: 'list object' has no attribute 'name'"}
```
可是我的list 裡面，不是已經定義了 name 這個屬性了嗎？為什麼說沒有 name 這個屬性？

**Comment by tsengeagle** [comment]
或許是變數宣告的方式差異
```yaml
  vars:
    bo_gw_nets:
      - name: hq
        bo_wan_networks: 1.1.1.0
```
![圖片](https://user-images.githubusercontent.com/6193596/54186140-a486ad80-44e5-11e9-8167-4090edec43ab.png)
