### ISSUE TITLE
用了 stat module & template module & when condition 去判斷是否要更新檔案內容

### ISSUE THREAD

**Issue by zarr12steven** [ansible-tw/AMA#43]
### OS Environment

```
# sw_vers                                                                                                                                                                                                        
ProductName:	    Mac OS X
ProductVersion:     10.14.5
BuildVersion:       18F132
```

### Ansible Version

```
ansible 2.8.1
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/Users/nobody/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /Library/Python/2.7/site-packages/ansible
  executable location = /usr/local/bin/ansible
  python version = 2.7.10 (default, Feb 22 2019, 21:55:15) [GCC 4.2.1 Compatible Apple LLVM 10.0.1 (clang-1001.0.37.14)]
```
### 使用情境說明

請問一下，用了 **stat** 去確認檔案存不存在，如果不存在，就建立，如果存在，就略過
但我現在有一個需求是…如果檔案存在，要怎麼更新檔案裡的內容？

### STEPS TO REPRODUCE

- task.yml

```
- hosts: remote
   tasks:
     - name: "Check /etc/motd is exists"
       stat:
         path: /etc/motd
       register: check_motd

     - name: "Create /etc/motd"
         template:
           src: etc/motd.j2
           dest: /etc/motd
           owner: root
           group: root
           mode: '0644'
         when:
           - not check_motd.stat.exists or MotdLoginBanner is defined
```

- motd.j2

```
{{ MotdLoginBanner }}
```

- 執行

```
ansible-playbook -i inventory task.yml -e MotdLoginBanner="Hello 9453"
```

多執行個幾次也不會有問題了

感謝 Ricky Lin  & Eric Chang 的幫忙
