### ISSUE TITLE
切換 Debian 軟體來源鏡像站的模組？

### ISSUE THREAD

**Issue by brlin-tw** [ansible-tw/AMA#46]
請問有模組可以切換 Debian/Ubuntu 使用的官方軟體庫鏡像站嗎？

我目前是用：

```yaml
    - name: Use taiwan mirror site as apt source
      command:
        argv:
          - sed
          - --in-place
          - '#//archive.ubuntu#//tw.archive.ubuntu#'
          - /etc/apt/sources.list
```
