### ISSUE TITLE
用來參照當前進行工作 task 名稱的變數？

### ISSUE THREAD

**Issue by brlin-tw** [ansible-tw/AMA#47]
請問有沒有變數是保存當前運行的 task 的名稱的，用於下列情境：

```yaml
    - name: 提高開檔與開進程數量限制
      pam_limits:
        dest: /etc/security/limits.d/increase-nofile-and-nproc-limits.conf
        comment: '{{變數名稱}}'
```
