### ISSUE TITLE
block 內的特定 task 不明原因被跳過，為什麼？

### ISSUE THREAD

**Issue by brlin-tw** [ansible-tw/AMA#52]
## 問題重現 playbook

```yaml
- name: repro
  hosts: all
  tasks:
    - name: 查詢 IPwatchD 當前最新釋出版本
      when: >
        ipwatchd_version is not defined
        or ipwatchd_version is none
        or ipwatchd_version == 'auto-detected'
      rescue:
        - name: 如果區塊內任一工作失敗視為區塊失敗
          fail:
            msg: 錯誤：查詢 IPwatchD 當前最新釋出版本期間發生錯誤
      block:
        - name: 查詢 IPwatchD 當前最新釋出版本：自 GitHub Releases API 查詢 IPwatchD 最新釋出資訊
          register: ipwatchd_version_latest_raw
          uri:
            url: https://api.github.com/repos/jariq/IPwatchD/releases/latest

        - name: 查詢 IPwatchD 當前最新釋出版本：自釋出資訊解析出當前 IPwatchD 最新版本
          set_fact:
            ipwatchd_version: '{{ ipwatchd_version_latest_raw.json.tag_name | replace("v", "") }}'

        - name: 查詢 IPwatchD 當前最新釋出版本：顯示查詢結果
          debug:
            msg: '當前最新釋出版本：{{ ipwatchd_version }}'
```

## 測試方式
```
ansible-playbook --connection=local -i localhost, playbook.yml 
```

## 預期結果
「查詢 IPwatchD 當前最新釋出版本：顯示查詢結果」task 有被執行

## 目前結果
「查詢 IPwatchD 當前最新釋出版本：顯示查詢結果」顯示為 skipped

## 環境
* Ansible 2.9.9
* Ubuntu 20.04
* Python 3.8.2
