### ISSUE TITLE
檢查目錄是否存在，並進行後續動作？

### ISSUE THREAD

**Issue by changchichung** [ansible-tw/AMA#54]
檢查 developer 的 HOME directory 是否已經存在 .pyenv 目錄
並註冊到 py_exist

```
- name: check if pyenv already been created
  stat:
    path: "/home/{{ item.name }}/.pyenv"
  register: py_exist
  when: 
    - inventory_hostname == item.nb or inventory_hostname == item.ws
  with_items: "{{ developers }}"
```
DEBUG
```
ok: [hqdc082.abc.com] => {
    "py_exist.results": [
        {
            "ansible_loop_var": "item",
            "changed": false,
            "failed": false,
            "invocation": {
                "module_args": {
                    "checksum_algorithm": "sha1",
                    "follow": false,
                    "get_attributes": true,
                    "get_checksum": true,
                    "get_md5": false,
                    "get_mime": true,
                    "path": "/home/userb/.pyenv"
                }
            },
            "item": {
                "dhome": "/home/userb/D",
                "name": "userb",
                "nb": "hqdc082.abc.com",
                "neohome": "/home/userb/D/neo",
                "ve": "/home/userb/D/neo/.ve",
                "ws": "hqs051.abc.com"
            },
            "stat": {
                "atime": 1616406615.2125473,
                "attr_flags": "e",
                "attributes": [
                    "extents"
                ],
                "block_size": 4096,
                "blocks": 8,
                "charset": "binary",
                "ctime": 1616403942.560995,
                "dev": 66309,
                "device_type": 0,
                "executable": true,
                "exists": true,
                "gid": 19000,
                "gr_name": "em",
                "inode": 4197789,
                "isblk": false,
                "ischr": false,
                "isdir": true,
                "isfifo": false,
                "isgid": false,
                "islnk": false,
                "isreg": false,
                "issock": false,
                "isuid": false,
                "mimetype": "inode/directory",
                "mode": "0755",
                "mtime": 1616403942.560995,
                "nlink": 14,
                "path": "/home/userb/.pyenv",
                "pw_name": "userb",
                "readable": true,
                "rgrp": true,
                "roth": true,
                "rusr": true,
                "size": 4096,
                "uid": 2305,
                "version": "3128321045",
                "wgrp": false,
                "woth": false,
                "writeable": true,
                "wusr": true,
                "xgrp": true,
                "xoth": true,
                "xusr": true
            }
        },
        {
            "ansible_loop_var": "item",
            "changed": false,
            "item": {
                "dhome": "/home/usera/D",
                "name": "usera",
                "nb": "hqdc081.abc.com",
                "neohome": "/home/usera/D/neo",
                "ve": "/home/usera/D/neo/.ve",
                "ws": "hqs053.abc.com"
            },
            "skip_reason": "Conditional result was False",
            "skipped": true
        }
    ]
}
```

上面的debug 可以看到變數 py_exist.results 裡面包含了 stat
所以我想用 py_exist.results.stat.exists 來判斷是否要執行task
```
- name: install pyenv from pyenv-installer
  become_user: "{{ item.item.name }}"
  shell: "curl -L https://raw.github.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash"
  when: not item.stat.exists
  with_items: "{{ py_exist.results }}"
 ```
但是會報錯，說沒有 stat 這個屬性？
```
fatal: [hqdc082.abc.com]: FAILED! => {"msg": "The conditional check 'not item.stat.exists' failed. The error was: error while evaluating conditional (not item.stat.exists): 'dict object' has no attribute 'stat'\n\nThe error appears to be in '/home/minion/D/ansiblecontrol/roles/pyenv/tasks/main.yml': line 26, column 3, but may\nbe elsewhere in the file depending on the exact syntax problem.\n\nThe offending line appears to be:\n\n\n- name: install pyenv from pyenv-installer\n  ^ here\n"}
```

請問該怎麼做才能正確取得 stat ？

**Comment by changchichung** [comment]
自問自答

因為 pyenv.results 裡面有兩組 item
然後因為其中一組 item 並沒有 stat 這個屬性，所以會報錯
要修正的話，就先檢查 item.stat 是否存在，應該就可以了

```
- name: install pyenv from pyenv-installer
  tags: debug
  become_user: "{{ item.item.name }}"
  shell: "curl -L https://raw.github.com/yyuu/pyenv-installer/master/bin/pyenv-installer | bash"
  with_items: "{{ py_exist.results }}"
  when:
    - item.stat is defined
    - not item.stat.exists                                                                             
```
