### ISSUE TITLE
關於回傳的list 被 [u ]  包住的問題

### ISSUE THREAD

**Issue by changchichung** [ansible-tw/AMA#55]
請問一個問題
我有一個yaml 檔案，大概像這樣

```yaml
{
    "teams": [
        {
            "chinese_name": "TEAM AA",
            "description": "AA Team",
            "gid": 10125,
            "location": [
                "hq"
            ],
            "name": "aa",
            "users": [
                "chu",
                "chou",
                "huyi",
                "way"
            ]
        },
		{
           "chinese_name": "TEAM BB",
           "description": "BB TEAM",
           "gid": 10126,
           "location": [
               "hq"
           ],
           "name": "bb",
           "users": [
               "chc",
               "lii",
               "lia",
               "xu",
               "link",
               "guo",
               "yan"
           ]
       },                                                      
	]
}
```
我想要取出 location 
但是每次回傳回來的都是一個被 [ ] 包起來的 list

task 長這樣

```yaml
- name: test
  tags: teams_test
  lineinfile:
    dest: "/tmp/{{ item[1].name }}/.teams"
    line: "{{ item[0].location }}-{{ item[0].name }}"
    create: yes
    state: present
  with_nested:
    - "{{ teams }}"
    - "{{ users }}"
  when: 
    - item[1].name is defined
    - item[0].users is defined
    - item[1].name in item[0].users                                          

```

產生的檔案內容如下

```
[u'hq']-hr
[u'hq']-nexushr
[u'hq']-omdata
```

我的疑問是為什麼傳回來的location 前後會被 [u''] 給包起來？
有沒有什麼filter 可以把這個[u''] 給拿掉？
我現在是用偷吃步，用 item[0].location[0] 去取值
那是因為我確定location 都是單一值，可是萬一將來出現多個值
或者是我想要改成取出 item[0].users 的時候就會碰到麻煩

不曉得有沒有什麼建議的方式？
